openapi: 3.0.1
info:
  title: BillingService_Mock
  description: API Definition of BillingService_Mock
  version: 1.0.0
servers:
- url: http://localhost:8290/billing
- url: https://localhost:8253/billing
paths:
  /account:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
